apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-data-tier
spec:
  replicas: 1
  template:
    metadata:
      name: rabbitmq-data-tier
      labels:
        app: rabbitmq
        tier: data
    spec:
      containers:
        - name: rabbitmq
          image: "rabbitmq:latest"
          ports:
          - containerPort: 5672