apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: work-dispatcher-tier
spec:
  replicas: 1
  template:
    metadata:
      name: work-dispatcher-tier
      labels:
        app: work-dispatcher
        tier: dispatcher
    spec:
      containers:
        - name: work-dispatcher
          image: "work-dispatcher:v1"
          ports:
          - containerPort: 8080